#!/usr/bin/env bash
# This script displays numbers from 1 to 20
# - Displays "4 and then bad luck from China" for the 4th iteration
# - Displays "9 and then bad luck from Japan" for the 9th iteration
# - Displays "17 and then bad luck from Italy" for the 17th iteration

counter=1
while [ "$counter" -le 20 ]
do
  case $counter in
    4)
      echo "$counter and then bad luck from China"  # 4 is unlucky in China
      ;;
    9)
      echo "$counter and then bad luck from Japan"  # 9 is unlucky in Japan
      ;;
    17)
      echo "$counter and then bad luck from Italy"  # 17 is unlucky in Italy
      ;;
    *)
      echo "$counter"
      ;;
  esac
  ((counter++))
done

